<?php
namespace Atst\Guzzle\Http\Plugin;

use Guzzle\Http\Plugin\BasicAuthPlugin;
use Guzzle\Http\Client;

/**
 * Test class for WsseAuthPlugin.
 * Generated by PHPUnit on 2012-01-18 at 11:43:33.
 */
class WsseAuthPluginTest extends \PHPUnit_Framework_TestCase
{
    /**
     */
    public function testAddsWsseAuthentication()
    {
        $plugin = new WsseAuthPlugin('michael', 'test');
        $client = new Client('http://www.test.com/');
        $client->getEventDispatcher()->addSubscriber($plugin);
        $request = $client->get('/');
        $headers = $request->getHeaders();
        $this->assertTrue(false !== $headers->hasKey('Authorization'));
        $this->assertTrue(false !== $headers->hasKey('X-WSSE'));
    }

    public function testAddsWsseAuthenticationWithCustomDigest()
    {
        $plugin = new WsseAuthPlugin('michael', 'test', function($nonce, $created, $password) {
            return 'this_digest_wont_work';
        });
        $client = new Client('http://www.test.com/');
        $client->getEventDispatcher()->addSubscriber($plugin);
        $request = $client->get('/');
        $headers = $request->getHeaders();
        $this->assertTrue(false !== $headers->hasKey('Authorization'));
        $this->assertTrue(false !== $headers->hasKey('X-WSSE'));
        $this->assertTrue(false !== strpos($headers->get('X-WSSE'), 'this_digest_wont_work'));
    }
}
?>
